CREATE DATABASE freeman;

USE freeman;

CREATE TABLE fm_project(
    proj_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '项目ID',
    creator_id INT NOT NULL DEFAULT 0 COMMENT '创建者ID',
    title VARCHAR(32) NOT NULL DEFAULT '' COMMENT '项目标题',
    intro TEXT NOT NULL COMMENT '项目简介',
    mission VARCHAR(32) NOT NULL DEFAULT '' COMMENT '使命',
    vision VARCHAR(32) NOT NULL DEFAULT '' COMMENT '愿景',
    value VARCHAR(32) NOT NULL DEFAULT '' COMMENT '价值观',
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (proj_id)
);

CREATE TABLE fm_group(
    group_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'group ID',
    creator_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建者ID',
    title VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'group标题',
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (group_id),
    KEY (creator_id)
);

CREATE TABLE fm_group_proj(
    group_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'group ID',
    proj_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '项目ID',
    join_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '加入时间',
    UNIQUE KEY(group_id, proj_id)
);

CREATE TABLE fm_user(
    uid INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'UserID', 
    unionid VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户unionid',
    avatar VARCHAR(256) NOT NULL DEFAULT '' COMMENT '用户头像',
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (uid),
    KEY (unionid)
);

CREATE TABLE fm_proj_member(
    uid INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'UserID',
    proj_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '项目ID',
    role TINYINT NOT NULL DEFAULT 0 COMMENT '角色',
    PRIMARY KEY(uid, proj_id),
    KEY(proj_id)
);

CREATE TABLE fm_canvas(
    proj_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '项目ID',
    detail TEXT NOT NULL COMMENT '细分',
    dtredactor_id INT UNSIGNED NULL DEFAULT '0' COMMENT '编辑者ID',
    dtupdate_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    painpoint TEXT NOT NULL COMMENT '痛点',
    ppredactor_id INT UNSIGNED NULL DEFAULT '0' COMMENT '编辑者ID',
    ppupdate_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    value TEXT NOT NULL COMMENT '价值',
    vlredactor_id INT UNSIGNED NULL DEFAULT '0' COMMENT '编辑者ID',
    vlupdate_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    scheme TEXT NOT NULL COMMENT '方案',
    scredactor_id INT UNSIGNED NULL DEFAULT '0' COMMENT '编辑者ID',
    scupdate_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    indicator TEXT NOT NULL COMMENT '指标',
    idcredactor_id INT UNSIGNED NULL DEFAULT '0' COMMENT '编辑者ID',
    idcupdate_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    income TEXT NOT NULL COMMENT '收入',
    icredactor_id INT UNSIGNED NULL DEFAULT '0' COMMENT '编辑者ID',
    icupdate_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    channel TEXT NOT NULL COMMENT '渠道',
    cnrecactor_id INT UNSIGNED NULL DEFAULT '0' COMMENT '编辑者ID',
    cnupdate_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    growth TEXT NOT NULL COMMENT '成长',
    gtredactor_id INT UNSIGNED NULL DEFAULT '0' COMMENT '编辑者ID',
    gtupdate_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (proj_id)
);

CREATE TABLE fm_card(
    card_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '卡片ID',
    proj_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '项目ID',
    canvas_id TINYINT NOT NULL DEFAULT 0 COMMENT '画布ID',
    title VARCHAR(32) NOT NULL DEFAULT '' COMMENT '卡片标题',
    assumption VARCHAR(64) NOT NULL DEFAULT '' COMMENT '假设',
    result VARCHAR(64) NOT NULL DEFAULT '' COMMENT '结果',
    start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '开始时间',
    end_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '结束时间',
    PRIMARY KEY (card_id),
    KEY (proj_id, canvas_id)
);

CREATE TABLE fm_wkreport(
    report_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '周报ID',
    proj_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '项目ID',
    week_no TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '周编号',
    content TEXT NOT NULL COMMENT '周报内容',
    redactor_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '编辑者ID',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (report_id),
    UNIQUE KEY (proj_id, week_no)
);

CREATE TABLE fm_mthrecord(
    record_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '月会ID',
    proj_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '项目ID',
    month_no TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '月编号',
    content TEXT NOT NULL COMMENT '月会总结',
    pdf_url VARCHAR(64) NOT NULL DEFAULT '' COMMENT '月会pdf',
    redactor_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '编辑者ID',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (record_id),
    UNIQUE KEY (proj_id, month_no)
);

CREATE TABLE fm_summary(
    summary_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '毕业总结ID',
    proj_id INT UNSIGNED NOT NULL DEFAULT 0 UNIQUE COMMENT '项目ID',
    photo_url VARCHAR(64) NOT NULL DEFAULT '' COMMENT '合影url',
    content TEXT NOT NULL COMMENT '毕业总结',
    redactor_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '编辑者ID',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (summary_id),
    KEY (proj_id)
);

CREATE TABLE fm_comment(
    comment_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '评论ID',
    commentor_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '评论者ID',
    proj_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '项目ID',
    target_id TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '评论对象ID',
    target_type TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '评论对象类型',
    content TEXT NOT NULL COMMENT '评论内容',
    submit_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '评论时间',
    PRIMARY KEY (comment_id),
    KEY (proj_id, target_id, target_type)
);

CREATE TABLE fm_reply(
    reply_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '回复ID',
    comment_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '评论ID',
    replier_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '回复者ID',
    content TEXT NOT NULL COMMENT '回复内容',
    submit_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '回复时间',
    PRIMARY KEY (reply_id),
    KEY (comment_id)
);

CREATE TABLE fm_card_comment(
    comment_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '评论ID',
    commentor_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '评论者ID',
    card_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '卡片ID',
    content TEXT NOT NULL COMMENT '评论内容',
    submit_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '评论时间',
    PRIMARY KEY (comment_id),
    KEY (card_id)
);

CREATE TABLE fm_card_reply(
    reply_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '回复ID',
    comment_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '评论ID',
    replier_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '回复者ID',
    content TEXT NOT NULL COMMENT '回复内容',
    submit_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '回复时间',
    PRIMARY KEY (reply_id),
    KEY (comment_id)
);
