CREATE DATABASE dq_freeman;

USE dq_freeman;

CREATE TABLE fm_user(
    uid INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'UserID', 
    unionid VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户unionid',
    nick_name VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户昵称',
    avatar VARCHAR(256) NOT NULL DEFAULT '' COMMENT '用户头像',
    role TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户角色',
    cur_proj INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '项目ID',
    cur_group INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '群组ID',
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (uid)
);

CREATE TABLE fm_group(
    group_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'group ID',
    creator_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建者ID',
    title VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'group标题',
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (group_id),
    KEY (creator_id)
);

CREATE TABLE fm_group_proj(
    group_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'group ID',
    proj_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '项目ID',
    join_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '加入时间',
    UNIQUE KEY(group_id, proj_id)
);

CREATE TABLE fm_project(
    proj_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '项目ID',
    creator_id INT NOT NULL DEFAULT 0 COMMENT '创建者ID',
    title VARCHAR(32) NOT NULL DEFAULT '' COMMENT '项目标题',
    intro TEXT NOT NULL COMMENT '项目简介',
    vision VARCHAR(32) NOT NULL DEFAULT '' COMMENT '愿景',
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (proj_id)
);

CREATE TABLE fm_proj_member(
    uid INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'UserID',
    proj_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '项目ID',
    is_creator TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否是项目发起人',
    PRIMARY KEY(uid, proj_id)
);

CREATE TABLE fm_pulse(
    item_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    proj_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '项目ID',
    pulse_id TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '脉搏ID',
    pulse_no INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '脉搏编号',
    content TEXT NOT NULL COMMENT '脉搏内容',
    redactor_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '编辑者ID',
    PRIMARY KEY (item_id),
    UNIQUE KEY (proj_id, pulse_id, pulse_no)
);

CREATE TABLE fm_canvas(
    insert_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    proj_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '项目ID',
    canvas_id TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '画布ID',
    redactor_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '编辑者ID',
    submit_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '提交时间',
    content TEXT NOT NULL COMMENT '内容',
    PRIMARY KEY (insert_id)
);

CREATE TABLE fm_card(
    card_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '卡片ID',
    card_order INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '卡片顺序',
    proj_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '项目ID',
    canvas_id TINYINT NOT NULL DEFAULT 0 COMMENT '画布ID',
    status VARCHAR(16) NOT NULL DEFAULT 'active' COMMENT '项目状态',
    title VARCHAR(32) NOT NULL DEFAULT '' COMMENT '卡片标题',
    assumption VARCHAR(64) NOT NULL DEFAULT '' COMMENT '假设',
    result VARCHAR(64) NOT NULL DEFAULT '' COMMENT '结果',
    start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '开始时间',
    PRIMARY KEY (card_id),
    KEY (proj_id, canvas_id)
);

CREATE TABLE fm_comment(
    comment_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '评论ID',
    commentor_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '评论者ID',
    proj_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '项目ID',
    field TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '评论对象字段',
    field_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '评论对象ID',
    content TEXT NOT NULL COMMENT '评论内容',
    submit_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '评论时间',
    PRIMARY KEY (comment_id),
    KEY (proj_id, field, field_id)
);

CREATE TABLE fm_reply(
    reply_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '回复ID',
    comment_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '评论ID',
    replier_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '回复者ID',
    content TEXT NOT NULL COMMENT '回复内容',
    submit_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '回复时间',
    PRIMARY KEY (reply_id),
    KEY (comment_id)
);

CREATE TABLE fm_marker(
    uid INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户ID',
    proj_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '项目ID',
    field TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '字段编号',
    field_id INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '字段ID',
    status TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否已读',
    UNIQUE KEY (uid, proj_id, field, field_id),
    KEY (uid, proj_id),
    KEY(proj_id)
);

